name: 'CycloneDX .NET Generate BOM'
author: Patrick Dwyer
description: 'Github action to generate a CycloneDX BOM for .NET projects'
inputs:
  path:
    description: 'The path to a .sln, .csproj, .vbproj, or packages.config file or the path to a directory which will be recursively analyzed for packages.config files'
    required: true
  out:
    description: 'Output directory'
    default: ./
    required: false
runs:
  using: 'node12'
  main: 'index.js'
